intelligent_customer:
    path:     /customer
    defaults: { _controller: IntelligentModuleBundle:Customer:index }
intelligent_customer_edit:
    path:     /customer/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Customer:edit }
intelligent_customer_view:
    path:     /customer/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Customer:view , page_no: 1 }
intelligent_customer_autocomplete:
    path:     /customer/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Customer:autocomplete}
intelligent_customerprojects:
    path:     /customerprojects
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:index }
intelligent_customerprojects_edit:
    path:     /customerprojects/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:edit }
intelligent_customerprojects_view:
    path:     /customerprojects/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:view , page_no: 1 }
intelligent_customerprojects_autocomplete:
    path:     /customerprojects/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:autocomplete}
intelligent_marketingprojects:
    path:     /marketingprojects
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:index }
intelligent_marketingprojects_edit:
    path:     /marketingprojects/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:edit }
intelligent_marketingprojects_view:
    path:     /marketingprojects/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:view , page_no: 1 }
intelligent_marketingprojects_autocomplete:
    path:     /marketingprojects/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:autocomplete }
intelligent_initiative:
    path:     /initiative
    defaults: { _controller: IntelligentModuleBundle:Initiative:index }
intelligent_initiative_edit:
    path:     /initiative/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Initiative:edit }
intelligent_initiative_view:
    path:     /initiative/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Initiative:view , page_no: 1 }
intelligent_initiative_autocomplete:
    path:     /initiative/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Initiative:autocomplete }
intelligent_campaign:
    path:     /campaign
    defaults: { _controller: IntelligentModuleBundle:Campaign:index }
intelligent_campaign_edit:
    path:     /campaign/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Campaign:edit }
intelligent_campaign_view:
    path:     /campaign/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Campaign:view , page_no: 1 }
intelligent_campaign_autocomplete:
    path:     /campaign/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Campaign:autocomplete }
intelligent_campaigncontacts:
    path:     /campaigncontacts
    defaults: { _controller: IntelligentModuleBundle:Campaigncontacts:index }
intelligent_campaigncontacts_edit:
    path:     /campaigncontacts/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Campaigncontacts:edit }
intelligent_campaigncontacts_view:
    path:     /campaigncontacts/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Campaigncontacts:view , page_no: 1 }
intelligent_campaigncontacts_autocomplete:
    path:     /campaigncontacts/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Campaigncontacts:autocomplete }
intelligent_psuedoemailaccounts:
    path:     /psuedoemailaccounts
    defaults: { _controller: IntelligentModuleBundle:Psuedoemailaccounts:index }
intelligent_psuedoemailaccounts_edit:
    path:     /psuedoemailaccounts/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Psuedoemailaccounts:edit }
intelligent_psuedoemailaccounts_view:
    path:     /psuedoemailaccounts/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Psuedoemailaccounts:view , page_no: 1 }
intelligent_psuedoemailaccounts_autocomplete:
    path:     /psuedoemailaccounts/autocomplete
intelligent_assignpsuedo:
    path:     /assignpsuedo
    defaults: { _controller: IntelligentModuleBundle:Assignpsuedo:index }
intelligent_assignpsuedo_edit:
    path:     /assignpsuedo/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Assignpsuedo:edit }
intelligent_assignpsuedo_view:
    path:     /assignpsuedo/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Assignpsuedo:view , page_no: 1 }
intelligent_assignpsuedo_autocomplete:
    path:     /assignpsuedo/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Assignpsuedo:autocomplete }
intelligent_links:
    path:     /links
    defaults: { _controller: IntelligentModuleBundle:Links:index }
intelligent_links_edit:
    path:     /links/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Links:edit }
intelligent_links_view:
    path:     /links/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Links:view , page_no: 1 }
intelligent_links_autocomplete:
    path:     /links/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Links:autocomplete }
intelligent_linkrates:
    path:     /linkrates
    defaults: { _controller: IntelligentModuleBundle:Linkrates:index }
intelligent_linkrates_edit:
    path:     /linkrates/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Linkrates:edit }
intelligent_linkrates_view:
    path:     /linkrates/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Linkrates:view , page_no: 1 }
intelligent_linkrates_autocomplete:
    path:     /linkrates/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Linkrates:autocomplete }
intelligent_dnclists:
    path:     /dnclists
    defaults: { _controller: IntelligentModuleBundle:Dnclists:index }
intelligent_dnclists_edit:
    path:     /dnclists/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Dnclists:edit }
intelligent_dnclists_view:
    path:     /dnclists/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Dnclists:view , page_no: 1 }
intelligent_dnclists_autocomplete:
    path:     /dnclists/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Dnclists:autocomplete }