intelligent_customer:
    path:     /customer
    defaults: { _controller: IntelligentModuleBundle:Customer:index }
intelligent_customer_edit:
    path:     /customer/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Customer:edit }
intelligent_customer_view:
    path:     /customer/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Customer:view , page_no: 1 }
intelligent_customer_delete:
    path:     /customer/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Customer:delete }
intelligent_customer_autocomplete:
    path:     /customer/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Customer:autocomplete}
intelligent_customer_fieldset:
    path:     /customer/fieldset
    defaults: { _controller: IntelligentModuleBundle:Customer:fieldset }
intelligent_customer_export:
    path:     /customer/export
    defaults: { _controller: IntelligentModuleBundle:Customer:export }
intelligent_customer_import:
    path:     /customer/import
    defaults: { _controller: IntelligentModuleBundle:Customer:import } 
    
intelligent_customerprojects:
    path:     /customerprojects
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:index }
intelligent_customerprojects_edit:
    path:     /customerprojects/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:edit }
intelligent_customerprojects_view:
    path:     /customerprojects/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:view , page_no: 1 }
intelligent_customerprojects_delete:
    path:     /customerprojects/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:delete }
intelligent_customerprojects_autocomplete:
    path:     /customerprojects/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:autocomplete}
intelligent_customerprojects_fieldset:
    path:     /customerprojects/fieldset
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:fieldset }
intelligent_customerprojects_export:
    path:     /customerprojects/export
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:export }
intelligent_customerprojects_import:
    path:     /customerprojects/import
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:import }
    
    
intelligent_marketingprojects:
    path:     /marketingprojects
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:index }
intelligent_marketingprojects_edit:
    path:     /marketingprojects/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:edit }
intelligent_marketingprojects_view:
    path:     /marketingprojects/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:view , page_no: 1 }
intelligent_marketingprojects_delete:
    path:     /marketingprojects/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:delete }
intelligent_marketingprojects_autocomplete:
    path:     /marketingprojects/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:autocomplete }
intelligent_marketingprojects_fieldset:
    path:     /marketingprojects/fieldset
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:fieldset }
intelligent_marketingprojects_export:
    path:     /marketingprojects/export
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:export }
intelligent_marketingprojects_import:
    path:     /marketingprojects/import
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:import }

intelligent_genric:
    path:     /genric
    defaults: { _controller: IntelligentModuleBundle:Genric:index }
intelligent_genric_edit:
    path:     /genric/edit/{module}/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Genric:edit }
intelligent_genric_view:
    path:     /genric/view/{module}/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Genric:view , page_no: 1 }
intelligent_genric_delete:
    path:     /genric/delete/{module}/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Genric:delete }
intelligent_genric_autocomplete:
    path:     /genric/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Genric:autocomplete }
intelligent_genric_fieldset:
    path:     /genric/fieldset/{module}
    defaults: { _controller: IntelligentModuleBundle:Genric:fieldset }
intelligent_genric_export:
    path:     /genric/export
    defaults: { _controller: IntelligentModuleBundle:Genric:export }
intelligent_genric_import:
    path:     /genric/import
    defaults: { _controller: IntelligentModuleBundle:Genric:import }