intelligent_customer:
    path:     /customer
    defaults: { _controller: IntelligentModuleBundle:Customer:index }
intelligent_customer_edit:
    path:     /customer/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Customer:edit }
intelligent_customer_view:
    path:     /customer/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Customer:view , page_no: 1 }
intelligent_customer_delete:
    path:     /customer/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Customer:delete }
intelligent_customer_autocomplete:
    path:     /customer/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Customer:autocomplete}
intelligent_customer_fieldset:
    path:     /customer/fieldset
    defaults: { _controller: IntelligentModuleBundle:Customer:fieldset }
intelligent_customer_export:
    path:     /customer/export
    defaults: { _controller: IntelligentModuleBundle:Customer:export }
intelligent_customer_import:
    path:     /customer/import
    defaults: { _controller: IntelligentModuleBundle:Customer:import } 
    
intelligent_customerprojects:
    path:     /customerprojects
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:index }
intelligent_customerprojects_edit:
    path:     /customerprojects/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:edit }
intelligent_customerprojects_view:
    path:     /customerprojects/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:view , page_no: 1 }
intelligent_customerprojects_delete:
    path:     /customerprojects/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:delete }
intelligent_customerprojects_autocomplete:
    path:     /customerprojects/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:autocomplete}
intelligent_customerprojects_fieldset:
    path:     /customerprojects/fieldset
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:fieldset }
intelligent_customerprojects_export:
    path:     /customerprojects/export
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:export }
intelligent_customerprojects_import:
    path:     /customerprojects/import
    defaults: { _controller: IntelligentModuleBundle:Customerprojects:import }
    
    
intelligent_marketingprojects:
    path:     /marketingprojects
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:index }
intelligent_marketingprojects_edit:
    path:     /marketingprojects/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:edit }
intelligent_marketingprojects_view:
    path:     /marketingprojects/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:view , page_no: 1 }
intelligent_marketingprojects_delete:
    path:     /marketingprojects/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:delete }
intelligent_marketingprojects_autocomplete:
    path:     /marketingprojects/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:autocomplete }
intelligent_marketingprojects_fieldset:
    path:     /marketingprojects/fieldset
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:fieldset }
intelligent_marketingprojects_export:
    path:     /marketingprojects/export
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:export }
intelligent_marketingprojects_import:
    path:     /marketingprojects/import
    defaults: { _controller: IntelligentModuleBundle:Marketingprojects:import }
    
intelligent_initiative:
    path:     /initiative
    defaults: { _controller: IntelligentModuleBundle:Initiative:index }
intelligent_initiative_edit:
    path:     /initiative/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Initiative:edit }
intelligent_initiative_view:
    path:     /initiative/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Initiative:view , page_no: 1 }
intelligent_initiative_delete:
    path:     /initiative/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Initiative:delete }
intelligent_initiative_autocomplete:
    path:     /initiative/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Initiative:autocomplete }
intelligent_initiative_fieldset:
    path:     /initiative/fieldset
    defaults: { _controller: IntelligentModuleBundle:Initiative:fieldset }
intelligent_initiative_export:
    path:     /initiative/export
    defaults: { _controller: IntelligentModuleBundle:Initiative:export }
    
    
intelligent_campaign:
    path:     /campaign
    defaults: { _controller: IntelligentModuleBundle:Campaign:index }
intelligent_campaign_edit:
    path:     /campaign/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Campaign:edit }
intelligent_campaign_view:
    path:     /campaign/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Campaign:view , page_no: 1 }
intelligent_campaign_delete:
    path:     /campaign/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Campaign:delete }
intelligent_campaign_autocomplete:
    path:     /campaign/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Campaign:autocomplete }
intelligent_campaign_fieldset:
    path:     /campaign/fieldset
    defaults: { _controller: IntelligentModuleBundle:Campaign:fieldset }
intelligent_campaign_export:
    path:     /campaign/export
    defaults: { _controller: IntelligentModuleBundle:Campaign:export }
intelligent_campaign_import:
    path:     /campaign/import
    defaults: { _controller: IntelligentModuleBundle:Campaign:import }  
    
intelligent_campaigncontacts:
    path:     /campaigncontacts
    defaults: { _controller: IntelligentModuleBundle:Campaigncontacts:index }
intelligent_campaigncontacts_edit:
    path:     /campaigncontacts/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Campaigncontacts:edit }
intelligent_campaigncontacts_view:
    path:     /campaigncontacts/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Campaigncontacts:view , page_no: 1 }
intelligent_campaigncontacts_delete:
    path:     /campaigncontacts/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Campaigncontacts:delete }
intelligent_campaigncontacts_autocomplete:
    path:     /campaigncontacts/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Campaigncontacts:autocomplete }
intelligent_campaigncontacts_fieldset:
    path:     /campaigncontacts/fieldset
    defaults: { _controller: IntelligentModuleBundle:Campaigncontacts:fieldset }
intelligent_campaigncontacts_export:
    path:     /campaigncontacts/export
    defaults: { _controller: IntelligentModuleBundle:Campaigncontacts:export }
intelligent_campaigncontacts_import:
    path:     /campaigncontacts/import
    defaults: { _controller: IntelligentModuleBundle:Campaigncontacts:import }
    
intelligent_psuedoemailaccounts:
    path:     /psuedoemailaccounts
    defaults: { _controller: IntelligentModuleBundle:Psuedoemailaccounts:index }
intelligent_psuedoemailaccounts_edit:
    path:     /psuedoemailaccounts/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Psuedoemailaccounts:edit }
intelligent_psuedoemailaccounts_view:
    path:     /psuedoemailaccounts/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Psuedoemailaccounts:view , page_no: 1 }
intelligent_psuedoemailaccounts_delete:
    path:     /psuedoemailaccounts/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Psuedoemailaccounts:delete }
intelligent_psuedoemailaccounts_autocomplete:
    path:     /psuedoemailaccounts/autocomplete
intelligent_psuedoemailaccounts_fieldset:
    path:     /psuedoemailaccounts/fieldset
    defaults: { _controller: IntelligentModuleBundle:Psuedoemailaccounts:fieldset }
intelligent_psuedoemailaccounts_export:
    path:     /psuedoemailaccounts/export
    defaults: { _controller: IntelligentModuleBundle:Psuedoemailaccounts:export }
intelligent_psuedoemailaccounts_import:
    path:     /psuedoemailaccounts/import
    defaults: { _controller: IntelligentModuleBundle:Psuedoemailaccounts:import } 
    
intelligent_assignpsuedo:
    path:     /assignpsuedo
    defaults: { _controller: IntelligentModuleBundle:Assignpsuedo:index }
intelligent_assignpsuedo_edit:
    path:     /assignpsuedo/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Assignpsuedo:edit }
intelligent_assignpsuedo_view:
    path:     /assignpsuedo/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Assignpsuedo:view , page_no: 1 }
intelligent_assignpsuedo_delete:
    path:     /assignpsuedo/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Assignpsuedo:delete }
intelligent_assignpsuedo_autocomplete:
    path:     /assignpsuedo/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Assignpsuedo:autocomplete }
intelligent_assignpsuedo_fieldset:
    path:     /assignpsuedo/fieldset
    defaults: { _controller: IntelligentModuleBundle:Assignpsuedo:fieldset }
intelligent_assignpsuedo_export:
    path:     /assignpsuedo/export
    defaults: { _controller: IntelligentModuleBundle:Assignpsuedo:export }
intelligent_assignpsuedo_import:
    path:     /assignpsuedo/import
    defaults: { _controller: IntelligentModuleBundle:Assignpsuedo:import }  
    
intelligent_links:
    path:     /links
    defaults: { _controller: IntelligentModuleBundle:Links:index }
intelligent_links_edit:
    path:     /links/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Links:edit }
intelligent_links_view:
    path:     /links/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Links:view , page_no: 1 }
intelligent_links_delete:
    path:     /links/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Links:delete }
intelligent_links_autocomplete:
    path:     /links/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Links:autocomplete }
intelligent_links_fieldset:
    path:     /links/fieldset
    defaults: { _controller: IntelligentModuleBundle:Links:fieldset }
intelligent_links_export:
    path:     /links/export
    defaults: { _controller: IntelligentModuleBundle:Links:export }
intelligent_links_import:
    path:     /links/import
    defaults: { _controller: IntelligentModuleBundle:Links:import }
    
intelligent_linkrates:
    path:     /linkrates
    defaults: { _controller: IntelligentModuleBundle:Linkrates:index }
intelligent_linkrates_edit:
    path:     /linkrates/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Linkrates:edit }
intelligent_linkrates_view:
    path:     /linkrates/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Linkrates:view , page_no: 1 }
intelligent_linkrates_delete:
    path:     /linkrates/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Linkrates:delete }
intelligent_linkrates_autocomplete:
    path:     /linkrates/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Linkrates:autocomplete }
intelligent_linkrates_fieldset:
    path:     /linkrates/fieldset
    defaults: { _controller: IntelligentModuleBundle:Linkrates:fieldset }
intelligent_linkrates_export:
    path:     /linkrates/export
    defaults: { _controller: IntelligentModuleBundle:Linkrates:export }
intelligent_linkrates_import:
    path:     /linkrates/import
    defaults: { _controller: IntelligentModuleBundle:Linkrates:import }
      
intelligent_dnclists:
    path:     /dnclists
    defaults: { _controller: IntelligentModuleBundle:Dnclists:index }
intelligent_dnclists_edit:
    path:     /dnclists/edit/{edit_id}
    defaults: { _controller: IntelligentModuleBundle:Dnclists:edit }
intelligent_dnclists_view:
    path:     /dnclists/view/{page_no}
    defaults: { _controller: IntelligentModuleBundle:Dnclists:view , page_no: 1 }
intelligent_dnclists_delete:
    path:     /dnclists/delete/{delete_id}
    defaults: { _controller: IntelligentModuleBundle:Dnclists:delete }
intelligent_dnclists_autocomplete:
    path:     /dnclists/autocomplete
    defaults: { _controller: IntelligentModuleBundle:Dnclists:autocomplete }
intelligent_dnclists_fieldset:
    path:     /dnclists/fieldset
    defaults: { _controller: IntelligentModuleBundle:Dnclists:fieldset }
intelligent_dnclists_export:
    path:     /dnclists/export
    defaults: { _controller: IntelligentModuleBundle:Dnclists:export }
intelligent_dnclists_import:
    path:     /dnclists/import
    defaults: { _controller: IntelligentModuleBundle:Dnclists:import }