services:
#    intelligent_module.example:
#        class: Intelligent\ModuleBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]


    intelligent.customer.module:
        class: Intelligent\ModuleBundle\Lib\Customer
        calls: 
            - [setContainer, ["@service_container"]]
            - [init]
    intelligent.customer_projects.module:
        class: Intelligent\ModuleBundle\Lib\Customerprojects
        calls: 
            - [setContainer, ["@service_container"]]
            - [init]            
    intelligent.marketing_projects.module:
        class: Intelligent\ModuleBundle\Lib\Marketingprojects
        calls: 
            - [setContainer, ["@service_container"]]
            - [init]     
    intelligent.import.module:
        class: Intelligent\ModuleBundle\Lib\Import
        calls: 
            - [setContainer, ["@service_container"]]