services:
#    intelligent_user.example:
#        class: Intelligent\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    
    user_permissions:
        class: Intelligent\UserBundle\Services\UserPermissions
        arguments: ["@security.token_storage","@doctrine"]
    entry_point.user_login:
        class: Intelligent\UserBundle\Services\LoginEntryPoint
        arguments: ["@router"]
    success.user_login:
        class: Intelligent\UserBundle\Services\LoginSuccessHandler
        arguments: ["@security.http_utils","@doctrine.orm.entity_manager"]