services:
#    intelligent_user.example:
#        class: Intelligent\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    
    controller_listener:
        class: Intelligent\UserBundle\Services\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller}
        arguments: ["@controller_resolver"]
    module_settings:
        class: Intelligent\SettingBundle\Lib\Settings
        arguments: ["@database_connection"]
    user_permissions:
        class: Intelligent\UserBundle\Services\UserPermissions
        arguments: ["@security.token_storage","@module_settings"]
    entry_point.user_login:
        class: Intelligent\UserBundle\Services\LoginEntryPoint
        arguments: ["@router"]
    success.user_login:
        class: Intelligent\UserBundle\Services\LoginSuccessHandler
        arguments: ["@security.http_utils","@doctrine.orm.entity_manager"]
    twig.module_permission:
        class: Intelligent\UserBundle\Extension\UserPermissionExtension
        arguments: ["@user_permissions"]
        public: false
        tags:
            - { name: twig.extension }