intelligent_user:
    resource: "@IntelligentUserBundle/Resources/config/routing.yml"
    prefix:   /

intelligent_module:
    resource: "@IntelligentModuleBundle/Resources/config/routing.yml"
    prefix:   /

intelligent_setting:
    resource: "@IntelligentSettingBundle/Resources/config/routing.yml"
    prefix:   /

intelligent_shared:
    resource: "@IntelligentSharedBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
