# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: 
#                users:
#                    tejaswi:  { password: chikoo@1, roles: 'ROLE_USER' }
        main:
            entity: 
                class: Intelligent\UserBundle\Entity\User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        reset_password_firewall:
            pattern: ^/resetPassword
            anonymous: ~
        api_general_firewall:
            pattern: ^/api/v1/general$
            anonymous: ~
        login_firewall:
            pattern: ^/login$
            anonymous: ~
        secured_area:
            pattern: ^/
            entry_point: entry_point.user_login
            form_login: 
                login_path: login
                check_path: login_check
            logout:
                path: /logout
                target: /login
            
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Intelligent\UserBundle\Entity\User: plaintext