# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    access_denied_url: /noaccess
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
#        in_memory:
#            memory: 
#                users:
#                    tejaswi:  { password: chikoo@1, roles: 'ROLE_USER' }
        main:
            entity: 
                class: Intelligent\UserBundle\Entity\User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        not_secured:
            pattern: ^/(resetPassword/[0-9a-z]+|api/v1/general|login|inviteUser/[0-9a-z]+)$
            security: false
        secured_area:
            pattern: ^/
            access_denied_url: /noaccess
            entry_point: entry_point.user_login
            form_login: 
                login_path: login
                check_path: login_check
                success_handler: success.user_login
            logout:
                path: /logout
                target: /login
                
    access_control:
        - { path: ^/users$ , roles: ROLE_USER_ADMIN }
        - { path: ^/roles$ , roles: ROLE_USER_ADMIN }
        - { path: ^/rolePermissions , roles: ROLE_USER_ADMIN }
        - { path: ^/settings/view , roles: ROLE_APP_ADMIN }
        - { path: ^/ , roles: ROLE_USER }
            
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Intelligent\UserBundle\Entity\User: plaintext