intelligent_setting_homepage:
    path:     /settings/
    defaults: { _controller: IntelligentSettingBundle:Default:index }
intelligent_setting_edit:
    path:     /settings/edit/{edit_id}
    defaults: { _controller: IntelligentSettingBundle:Default:edit }
intelligent_setting_delete:
    path:     /settings/delete/{delete_id}
    defaults: { _controller: IntelligentSettingBundle:Default:delete }
intelligent_setting_view:
    path:     /settings/view/
    defaults: { _controller: IntelligentSettingBundle:Default:view }