services:
#    intelligent_setting.example:
#        class: Intelligent\SettingBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    intelligent.setting.module:
        class: Intelligent\SettingBundle\Lib\Settings
        calls: 
            - [setContainer, [@service_container]]
            - [init]